### ISSUE TITLE
Migration does not work for some dmn diagrams

### ISSUE THREAD

**Issue by OmranAbazid** [bpmn-io/dmn-migrate#18] opened 2020-03-05 12:47 UTC
__Steps to Reproduce__

1. Try to migrate this diagram [diagram11.dmn.zip](https://github.com/bpmn-io/dmn-migrate/files/4292980/diagram11.dmn.zip) using the migration tool
2. The migration fails with the following error
![image](https://user-images.githubusercontent.com/9063094/75982803-abbd7d00-5ee7-11ea-8fef-1bf5e52f484d.png)

__Environment__

- OS: Mac OSX
- Library version: "dmn-js": "^8.0.1"

**Comment by nikku** [comment] 2020-03-05 14:44
Root cause analysis:

* the diagram is broken, as it contains a `biodi:Edge` with a non-existing source
* it seems like we've generated such diagram at some point in time
* :arrow_right: we should handle the situation gracefully

**Comment by nikku** [comment] 2020-03-05 14:45
Will be fixed via https://github.com/bpmn-io/dmn-migrate/pull/19.

Thanks for your bug report.

**Closed** 2020-03-06 08:40 UTC
Labels: bug, needs review

**Comment by nikku** [comment] 2020-03-06 08:44
Fixed with `v0.4.3`.
